### ISSUE TITLE
Timeline for Code Release 

### ISSUE THREAD

**Issue by taeyeopl** [JiehongLin/SAM-6D#1]
May I ask for a rough timeline for releasing the code?

**Comment by JiehongLin** [comment]
Thanks for your interest in our work. We are currently in the process of organizing the codes and aim to release them in two weeks.

**Comment by taeyeopl** [comment]
Thanks :) I'm looking forward to the codes soon!

**Comment by lcl-git-3d** [comment]
Hi,thanks for creating such a great job! Will you provide detailed environment configuration methods and training, testing, and visualization code?

**Comment by JiehongLin** [comment]
Hi, we have provided detailed environment configurations in [link](https://github.com/JiehongLin/SAM-6D/blob/main/SAM-6D/environment.yaml).
