### ISSUE TITLE
FileNotFoundError: No such file: '/SAM-6D/SAM-6D/Pose_Estimation_Model/Data/Example/outputs/templates/rgb_0.png'

### ISSUE THREAD

**Issue by aThinkingNeal** [JiehongLin/SAM-6D#11]
I have been following the instructions and encountered this error.

It seems the file path are not updated accordingly in the codebase.

The error screenshot is attached.

![image](https://github.com/JiehongLin/SAM-6D/assets/31988374/0d9352b3-3377-4bae-9920-175bbad71a47)

**Comment by foollh** [comment]
1. It seems that the dependency library for blender is missing, you can run this command `apt-get install libxrender1` to install it.
2. We have updated the module path in codebase, please download the latest code and try again.
If you encounter any other related problems, please do not hesitate to ask.

**Comment by 52THANOS** [comment]
> 1. It seems that the dependency library for blender is missing, you can run this command `apt-get install libxrender1` to install it.
> 2. We have updated the module path in codebase, please download the latest code and try again.
>    If you encounter any other related problems, please do not hesitate to ask.

if i ran this project in windows , how can i solve the same issue.
