### ISSUE TITLE
Docker + No such file: '/workspace/SAM-6D/SAM-6D/Pose_Estimation_Model/Data/Example/outputs/templates/rgb_0.png'

### ISSUE THREAD

**Issue by fedona** [JiehongLin/SAM-6D#16]
Hello, thank you for sharing your work!
I am eager to run the demo and test it, but I am encountering some issues.

This in my log when i run the demo (after having prepared the environment):

(sam6d) root@4e857b3a8101:/workspace/SAM-6D/SAM-6D# bash demo.sh 
Warning: Changed install path from /home_local/root... to /root..., there is no /home_local/ on this machine.
Using blender in /root/blender/blender-3.5.1-linux-x64
Using temporary directory: /dev/shm/blender_proc_a4853766307743d9950cdd915122e0f6
Blender 3.5.1 (hash e1ccd9d4a1d3 built 2023-04-24 23:31:15)
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
/root/blender/blender-3.5.1-linux-x64/3.5/python/lib/python3.10/site-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/root/blender/blender-3.5.1-linux-x64/3.5/python/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/root/blender/blender-3.5.1-linux-x64/3.5/python/lib/python3.10/site-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/root/blender/blender-3.5.1-linux-x64/3.5/python/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Selecting render devices...
Device NVIDIA GeForce RTX 2080 of type CUDA found and used.
Device Intel Core i7-9700K CPU @ 3.60GHz of type CPU found and used.
Error: Python: Traceback (most recent call last):
  File "/workspace/SAM-6D/SAM-6D/Render/render_custom_templates.py", line 42, in <module>
    scale = get_norm_info(args.cad_path)
  File "/workspace/SAM-6D/SAM-6D/Render/render_custom_templates.py", line 24, in get_norm_info
    mesh = trimesh.load(mesh_path, force='mesh')
  File "/root/blender/blender-3.5.1-linux-x64/custom-python-packages/lib/python3.10/site-packages/trimesh/exchange/load.py", line 116, in load
    ) = parse_file_args(file_obj=file_obj,
  File "/root/blender/blender-3.5.1-linux-x64/custom-python-packages/lib/python3.10/site-packages/trimesh/exchange/load.py", line 630, in parse_file_args
    raise ValueError('string is not a file: {}'.format(file_obj))
ValueError: string is not a file: Data/Example/obj_000005.ply

Error: script failed, file: 'render_custom_templates.py', exiting.
Cleaning temporary directory
INFO:root:Initializing model
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmpsnisnid3
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmpsnisnid3/_remote_module_non_scriptable.py
INFO:root:Loading SAM model from ./checkpoints/segment-anything/
INFO:root:Init CustomSamAutomaticMaskGenerator done!
INFO:dinov2:using MLP layer as FFN
INFO:root:Init CustomDINOv2 done!
INFO:root:Init CustomDINOv2 with full size=640 and proposal size=224 done!
INFO:root:Init CNOS done!
INFO:root:Moving models to cuda done!
INFO:root:Initializing template
Traceback (most recent call last):
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/run_inference_custom.py", line 212, in <module>
    run_inference(
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/run_inference_custom.py", line 128, in run_inference
    templates = torch.stack(templates).permute(0, 3, 1, 2)
RuntimeError: stack expects a non-empty TensorList
set CUDA_VISIBLE_DEVICES as 0
=> creating model ...
load pre-trained checkpoint from: checkpoints/mae_pretrain_vit_base.pth
=> extracting templates ...
Traceback (most recent call last):
  File "/workspace/SAM-6D/SAM-6D/Pose_Estimation_Model/run_inference_custom.py", line 276, in <module>
    all_tem, all_tem_pts, all_tem_choose = get_templates(tem_path, cfg.test_dataset)
  File "/workspace/SAM-6D/SAM-6D/Pose_Estimation_Model/run_inference_custom.py", line 160, in get_templates
    tem, tem_choose, tem_pts = _get_template(path, cfg, i)
  File "/workspace/SAM-6D/SAM-6D/Pose_Estimation_Model/run_inference_custom.py", line 124, in _get_template
    rgb = load_im(rgb_path).astype(np.uint8)
  File "/workspace/SAM-6D/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/utils/data_utils.py", line 15, in load_im
    im = imageio.imread(path)
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/imageio/__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/imageio/v2.py", line 359, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/imageio/core/imopen.py", line 113, in imopen
    request = Request(uri, io_mode, format_hint=format_hint, extension=extension)
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/imageio/core/request.py", line 247, in __init__
    self._parse_uri(uri)
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/imageio/core/request.py", line 407, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/workspace/SAM-6D/SAM-6D/Pose_Estimation_Model/Data/Example/outputs/templates/rgb_0.png'

I have already seen a similar issue in #11 but I have libxrender already installed.
It might be good to mention that I am running it on a docker container with Ubuntu 20.04 and cuda 11.7

Would you consider providing a docker image for running your code?

Thanks

**Comment by foollh** [comment]
Thank you for raising this issue, we have not encountered this problem before. It looks like the template was not rendered successfully. We suggest you check that the `blenderproc quickstart` command is running successfully and that our version of blenderproc is 2.6.1.

We had plans to release the docker, and unsurprisingly we will be releasing the docker in the next few days.

**Comment by gachiemchiep** [comment]
@fedona 
you need to set the paths into absolute value. 

```bash
export CAD_PATH=$PWD/Data/Example/obj_000005.ply    # path to a given cad model(mm)
export RGB_PATH=$PWD/Data/Example/rgb.png           # path to a given RGB image
export DEPTH_PATH=$PWD/Data/Example/depth.png       # path to a given depth map(mm)
export CAMERA_PATH=$PWD/Data/Example/camera.json    # path to given camera intrinsics
export OUTPUT_DIR=$PWD/Data/Example/outputs         # path to a pre-defined file for saving results
```

The reason is inside  demo.sh

```bash
cd Render
blenderproc run render_custom_templates.py --output_dir $OUTPUT_DIR --cad_path $CAD_PATH
# at this step  $CAD_PATH is still Data/Example/obj_000005.ply and it is wrong
# the correct value should be ../Data/Example/obj_000005.ply 
```

**Comment by fedona** [comment]
> Thank you for raising this issue, we have not encountered this problem before. It looks like the template was not rendered successfully. We suggest you check that the `blenderproc quickstart` command is running successfully and that our version of blenderproc is 2.6.1.
> 
> We had plans to release the docker, and unsurprisingly we will be releasing the docker in the next few days.

Thank you! I will be waiting for it

**Comment by fedona** [comment]
> @fedona you need to set the paths into absolute value.
> 
> ```shell
> export CAD_PATH=$PWD/Data/Example/obj_000005.ply    # path to a given cad model(mm)
> export RGB_PATH=$PWD/Data/Example/rgb.png           # path to a given RGB image
> export DEPTH_PATH=$PWD/Data/Example/depth.png       # path to a given depth map(mm)
> export CAMERA_PATH=$PWD/Data/Example/camera.json    # path to given camera intrinsics
> export OUTPUT_DIR=$PWD/Data/Example/outputs         # path to a pre-defined file for saving results
> ```
> 
> The reason is inside demo.sh
> 
> ```shell
> cd Render
> blenderproc run render_custom_templates.py --output_dir $OUTPUT_DIR --cad_path $CAD_PATH
> # at this step  $CAD_PATH is still Data/Example/obj_000005.ply and it is wrong
> # the correct value should be ../Data/Example/obj_000005.ply 
> ```

Thank you, now works!
