### ISSUE TITLE
Custom Data, vis_pem.png not matching.

### ISSUE THREAD

**Issue by kevinDrawn** [JiehongLin/SAM-6D#21]
Hello, I'm struggling to adapt the sam-6d on my custom data.

ISM is work perfectly. But PEM is abnormal.
![image](https://github.com/JiehongLin/SAM-6D/assets/128012358/abe0a41a-333d-4655-909a-1cb5055d9401)
![image](https://github.com/JiehongLin/SAM-6D/assets/128012358/97ea7166-6306-4004-9b97-a12e9fd303b0)

why this PEM precision is worst?

My 3D Model is normal. 

![Screenshot from 2024-02-27 01-24-50](https://github.com/JiehongLin/SAM-6D/assets/128012358/00d068a8-9264-4f14-a354-e609fcafa012)

Can you suggest some idea?
@JiehongLin

**Comment by foollh** [comment]
It seems to me that you should check the units of CAD and depth. The input CAD and depth in this demo are both in millimeters.

**Comment by kevinDrawn** [comment]
Thank you for reply. I checked my CAD and Depth images. There were two problem.

1. vertex unit of CAD was set to 'm'. So I changed to 'mm'.
2. My Depth Camera(D455) scale is 0.001. But, it makes worst.

`whole_depth = load_im(depth_path).astype(np.float32) * cam_info['depth_scale'] / 1000.0 `
When I set my depth_scale to 0.001, whole_depth value was nearly 10^-6. It is very different with example depth data which has 10^-3. So I changed my depth_scale 0.001 to 1. 

But PEM precision did not change. I think it is not changed.

![image](https://github.com/JiehongLin/SAM-6D/assets/128012358/47775c59-55e5-4a7c-b290-c1a6325d7c97)

I have attached my input model. Thank you. Template data is inside of the 'output' folder.

Thank you a lot!

[input_data.tar.gz](https://github.com/JiehongLin/SAM-6D/files/14421251/input_data.tar.gz)

**Comment by foollh** [comment]
I have evaluated the data you provided, and the pose estimate is exactly accurate, as shown in the figure below.  The yellow points represent the point cloud of CAD transformed by the predicted pose, and align with the red points cropped from the observed point cloud. 

<img width="797" alt="vis" src="https://github.com/JiehongLin/SAM-6D/assets/58074418/4d63af58-5776-47e5-ad61-aab6b01cb9a1">

The 3D bounding box seems to be wrong because the original CAD is not semantically aligned, as shown in the figure. We have added the visualization code for the model point projection. You can try it again.

<img width="406" alt="proj" src="https://github.com/JiehongLin/SAM-6D/assets/58074418/3d15b4ef-3399-4dd6-b93a-edb34baa92a8">

**Comment by kevinDrawn** [comment]
WOW. Amazing. Thank you so much!!

Do you mean then even though the visualization box has problem, the Pose Estimation Value (R, T) is correct?

I checked the "scale" in Pose_Estimation_Model/run_inference_custom.py
`scale = np.max(np.abs(model_points), axis=0)*2 * 1000`

the scale output was [295.84, 170.18, 408.63].
However, my 3D model dimension is [210 240 65] mm.
I think that the system sampled points in wrong place. Is it occured sementical issue??

Thank you a lot!
![image](https://github.com/JiehongLin/SAM-6D/assets/128012358/f666d901-3f67-4ed2-9902-30ddb2fd12a2)

ps. How can you evaluate my cad data? Is is provided in this repo?

**Comment by foollh** [comment]
Yes. The semantic issue means the 3d bounding box calculated in the current CAD coordinate system does not closely fit the mesh. You can change the CAD coordinate system before input to solve this problem.

The data I evaluated are from the link you gave in this comment.

> Thank you for reply. I checked my CAD and Depth images. There were two problem.
> 
> 1. vertex unit of CAD was set to 'm'. So I changed to 'mm'.
> 2. My Depth Camera(D455) scale is 0.001. But, it makes worst.
> 
> `whole_depth = load_im(depth_path).astype(np.float32) * cam_info['depth_scale'] / 1000.0 ` When I set my depth_scale to 0.001, whole_depth value was nearly 10^-6. It is very different with example depth data which has 10^-3. So I changed my depth_scale 0.001 to 1.
> 
> But PEM precision didn't improve.
> 
> ![image](https://private-user-images.githubusercontent.com/128012358/308218820-47775c59-55e5-4a7c-b290-c1a6325d7c97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTI0MDMsIm5iZiI6MTcwOTExMjEwMywicGF0aCI6Ii8xMjgwMTIzNTgvMzA4MjE4ODIwLTQ3Nzc1YzU5LTU1ZTUtNGE3Yy1iMjkwLWMxYTYzMjVkN2M5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQwOTIxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2JkYjY5MWM0YjhkMjMxYWI3MGUxMmExNzc1M2Q0M2EwMjQ2NzlkZDE1OWQxZThmNDIzOGNlYzQ2Njk5ZDViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p2So8lJR2YUWiraJ4Redco5AMhTKY5iRpBpodbdcyCY)
> 
> I have attached my input model.
> 
> Thank you a lot!
> 
> [input.tar.gz](https://github.com/JiehongLin/SAM-6D/files/14421798/input.tar.gz)

**Comment by kevinDrawn** [comment]
Thank you so much! I solved my problem!
