### ISSUE TITLE
Run demo.sh error:torch.cuda.OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by starry-wf** [JiehongLin/SAM-6D#22]
when I run demo.sh, Instance_Segmentation_Model/run_inference_custom.py was an error.

![cuda error](https://github.com/JiehongLin/SAM-6D/assets/53518371/ffc70eaa-4eb0-4b73-a7ab-d98ed817ccca)

**Comment by kevinDrawn** [comment]
This error occure when SAM-6D need to use over your computer memory. What is your Graphic Card Model?

**Comment by JiehongLin** [comment]
Hi, it may be caused by the memory consumption of SAM.  You may choose FastSAM for SAM-6D.

**Comment by starry-wf** [comment]
> Hi, it may be caused by the memory consumption of SAM. You may choose FastSAM for SAM-6D.

OK，thanks
