### ISSUE TITLE
It is not realized to Visualize the FastSAM + Why it takes same time before?

### ISSUE THREAD

**Issue by kevinDrawn** [JiehongLin/SAM-6D#28]
Thank you for your Great Work!

It is not realized to Visualize the FastSAM ?

There is no visualization mask.

And I feel that It takes same time either with or without FastSAM. Inference time for PEM be longer.

Before adding the FastSAM Function, Inference time takes 28~30 second.

However, It takes nearly 30 seconds with FastSAM.

Did you change the Batch Size?? Memory usage be lower. Average memory Usage is 2888MB.

Prior to new version, Maximum Memry Usage was 9000MB 

![image](https://github.com/kevinDrawn/sam6d_data/assets/128012358/0083f42f-5b1c-466e-a2eb-0d6f95139aae)

**Comment by foollh** [comment]
Sorry, I can't display the image here. Can you please upload it again?

**Comment by kevinDrawn** [comment]
![image](https://github.com/JiehongLin/SAM-6D/assets/128012358/a238c1dd-7b1a-4f93-8f2c-adf819ba1fb0)

And then It takes long time during

`/SAM-6D/SAM-6D/Instance_Segmentation_Model/run_inference_custom.py:86: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  depth = np.array(imageio.imread(depth_path)).astype(np.int32)`

Maximum Memory Usage is 2888MB. It's a really low number. I think it makes process be longer. I want to save the inference time.
![image](https://github.com/JiehongLin/SAM-6D/assets/128012358/eedff466-496f-4b8c-aac7-816db4da4d53)

Thank you !

**Comment by foollh** [comment]
In ISM, FastSAM does not perform better than SAM. If the final segmentation result is not good, please replace it with SAM or adjust the hyparameters of FastSAM.
In my opinion, the reason why the inference time has not become faster may be due to the failure of FastSAM prediction.

**Comment by kevinDrawn** [comment]
![vis_ism](https://github.com/JiehongLin/SAM-6D/assets/128012358/bc9a81de-b955-4a64-997e-069bc4bdc660)

FastSAM Segmentation is clear! 

But, OOM problem occured. 
In SAM model, OOM can be solved by changing the batch size with Below method.
https://github.com/JiehongLin/SAM-6D/issues/24#issuecomment-1981038102

I can't find change batch size for reducing memory usage.

**Comment by foollh** [comment]
You can change the fastsam hyperparamers in [fast_sam.yaml](https://github.com/JiehongLin/SAM-6D/blob/main/SAM-6D/Instance_Segmentation_Model/configs/model/segmentor_model/fast_sam.yaml) or directly set the `det_score_thresh` higher in [run_inference_custom.py](https://github.com/JiehongLin/SAM-6D/blob/main/SAM-6D/Pose_Estimation_Model/run_inference_custom.py) to reduce the input batch in PEM. 
If you want to speed up inference, you can try adjusting the hyperparameters of ISM and PEM, such as adjusting `det_score_thresh` to only input one segmentation result to PEM.

**Comment by kevinDrawn** [comment]
Thank you! I solved the oom problem by inceasing the det_score_thresh in PEM run_infernece_custom.py. 

Where do i increase the det_score_thresh of ISM? 

[detection_ism.json](https://github.com/JiehongLin/SAM-6D/files/14574702/detection_ism.json)

There's too much Segmentation Instance. I want to increase det_threshold of ISM.

I try to tune it

1. fast_sam.yaml
- reduce max_det
- increase conf_threshold 

2. ISM_fastsam.yaml
- matching_config
      confidence_thresh: 0.2 -> increase

It did not short the inference time.
It is consumed more time than sam.

Can you suggest any specific parameter to shorten inference time??
 
In the "sam-6d" Paper, inference time is very short.
![Screenshot from 2024-03-13 00-18-27](https://github.com/JiehongLin/SAM-6D/assets/128012358/b6c9c994-fb41-4915-9bc7-27004e49c37f)

My another computer GPU is  NVIDIA RTX A6000 48GB. 
But It consumed same inference time.

**Comment by foollh** [comment]
The inference times reported in the paper for ISM and PEM only include model forward time. But the demo contains many parts, such as model registration, template rendering and feature extraction. These steps take a lot of time during initialization.

**Comment by kevinDrawn** [comment]
Can I save the feature data of the 3D model? Afterward inference can be done? without feature extraction process??

Thank you!

**Comment by foollh** [comment]
Yes, you can save the features of 3D model templates locally. When a new image appears, you can directly load the features without reruning the feature extraction network for the model.

**Comment by kevinDrawn** [comment]
Ohh! Really? Can you explain how to do it?

**Comment by foollh** [comment]
Sorry, I currently have no ideas for speeding up model initialization in our demo.

**Comment by kevinDrawn** [comment]
Thank you !! I received a lot of help.

Have a nice Day~~!

**Comment by Rain-BBking** [comment]
> 我创立了跳过模板功能过程的方法！
> 
> 我还有另一个问题。每次，我都必须初始化 model。这需要一些时间。
> 
> 我不能像模板一样存储这个过程吗？

Hello, I'd like to ask you how you do this part about saving features to speed up predictions
