### ISSUE TITLE
No module named 'trimesh'

### ISSUE THREAD

**Issue by 52THANOS** [JiehongLin/SAM-6D#31]
I HAVE INSTALLED this package,  but script still can not find it

  File "<string>", line 1, in <module>
  File "H:\SAM-6D\venv\lib\site-packages\blenderproc\scripts\quickstart.py", line 11, in <module>
    import blenderproc as bproc
  File "H:\SAM-6D\venv\lib\site-packages\blenderproc\__init__.py", line 21, in <module>
    from .api import loader
  File "H:\SAM-6D\venv\lib\site-packages\blenderproc\api\loader\__init__.py", line 1, in <module>
    from blenderproc.python.loader.AMASSLoader import load_AMASS
  File "H:\SAM-6D\venv\lib\site-packages\blenderproc\python\loader\AMASSLoader.py", line 15, in <module>
    from blenderproc.python.types.MeshObjectUtility import MeshObject
  File "H:\SAM-6D\venv\lib\site-packages\blenderproc\python\types\MeshObjectUtility.py", line 12, in <module>
    from trimesh import Trimesh
ModuleNotFoundError: No module named 'trimesh'

**Comment by 52THANOS** [comment]
wrong python environment

**Comment by Wangcasc** [comment]
> I HAVE INSTALLED this package, but script still can not find it
> 
> File "", line 1, in File "H:\SAM-6D\venv\lib\site-packages\blenderproc\scripts\quickstart.py", line 11, in import blenderproc as bproc File "H:\SAM-6D\venv\lib\site-packages\blenderproc__init__.py", line 21, in from .api import loader File "H:\SAM-6D\venv\lib\site-packages\blenderproc\api\loader__init__.py", line 1, in from blenderproc.python.loader.AMASSLoader import load_AMASS File "H:\SAM-6D\venv\lib\site-packages\blenderproc\python\loader\AMASSLoader.py", line 15, in from blenderproc.python.types.MeshObjectUtility import MeshObject File "H:\SAM-6D\venv\lib\site-packages\blenderproc\python\types\MeshObjectUtility.py", line 12, in from trimesh import Trimesh ModuleNotFoundError: No module named 'trimesh'

Hello, I'm having the same problem, but I already have trimesh in my python environment. How did you solve it?

**Comment by HITXCI** [comment]
> > I HAVE INSTALLED this package, but script still can not find it
> > File "", line 1, in File "H:\SAM-6D\venv\lib\site-packages\blenderproc\scripts\quickstart.py", line 11, in import blenderproc as bproc File "H:\SAM-6D\venv\lib\site-packages\blenderproc__init__.py", line 21, in from .api import loader File "H:\SAM-6D\venv\lib\site-packages\blenderproc\api\loader__init__.py", line 1, in from blenderproc.python.loader.AMASSLoader import load_AMASS File "H:\SAM-6D\venv\lib\site-packages\blenderproc\python\loader\AMASSLoader.py", line 15, in from blenderproc.python.types.MeshObjectUtility import MeshObject File "H:\SAM-6D\venv\lib\site-packages\blenderproc\python\types\MeshObjectUtility.py", line 12, in from trimesh import Trimesh ModuleNotFoundError: No module named 'trimesh'
> 
> Hello, I'm having the same problem, but I already have trimesh in my python environment. How did you solve it?

Hi! I got the same issue, did you have any idea to solve it?

**Comment by zhangsong1213** [comment]
> > > I HAVE INSTALLED this package, but script still can not find it
> > > File "", line 1, in File "H:\SAM-6D\venv\lib\site-packages\blenderproc\scripts\quickstart.py", line 11, in import blenderproc as bproc File "H:\SAM-6D\venv\lib\site-packages\blenderproc__init__.py", line 21, in from .api import loader File "H:\SAM-6D\venv\lib\site-packages\blenderproc\api\loader__init__.py", line 1, in from blenderproc.python.loader.AMASSLoader import load_AMASS File "H:\SAM-6D\venv\lib\site-packages\blenderproc\python\loader\AMASSLoader.py", line 15, in from blenderproc.python.types.MeshObjectUtility import MeshObject File "H:\SAM-6D\venv\lib\site-packages\blenderproc\python\types\MeshObjectUtility.py", line 12, in from trimesh import Trimesh ModuleNotFoundError: No module named 'trimesh'
> > 
> > 
> > Hello, I'm having the same problem, but I already have trimesh in my python environment. How did you solve it?
> 
> Hi! I got the same issue, did you have any idea to solve it?

I have the same issue too

**Comment by HITXCI** [comment]
Hi! I found the solution, BlenderProc and Conda were not using the same Python environment, so needed to use "blenderproc pip install [package-name]".
















At 2025-07-07 08:53:36, "Zhangs" ***@***.***> wrote:

zhangsong1213 left a comment (JiehongLin/SAM-6D#31)

I HAVE INSTALLED this package, but script still can not find it
File "", line 1, in File "H:\SAM-6D\venv\lib\site-packages\blenderproc\scripts\quickstart.py", line 11, in import blenderproc as bproc File "H:\SAM-6D\venv\lib\site-packages\blenderproc__init__.py", line 21, in from .api import loader File "H:\SAM-6D\venv\lib\site-packages\blenderproc\api\loader__init__.py", line 1, in from blenderproc.python.loader.AMASSLoader import load_AMASS File "H:\SAM-6D\venv\lib\site-packages\blenderproc\python\loader\AMASSLoader.py", line 15, in from blenderproc.python.types.MeshObjectUtility import MeshObject File "H:\SAM-6D\venv\lib\site-packages\blenderproc\python\types\MeshObjectUtility.py", line 12, in from trimesh import Trimesh ModuleNotFoundError: No module named 'trimesh'

Hello, I'm having the same problem, but I already have trimesh in my python environment. How did you solve it?

Hi! I got the same issue, did you have any idea to solve it?

I have the same issue too
