### ISSUE TITLE
Missing demo files

### ISSUE THREAD

**Issue by plusgrey** [JiehongLin/SAM-6D#33]
Hi Jiehong, thanks for your great work. However, when I run the demo.sh, it tells that there is a missing file. Could you please help me with it?
![image](https://github.com/JiehongLin/SAM-6D/assets/56119958/a22d350f-a7d2-4a0e-9ef1-1329de83b906)

**Comment by plusgrey** [comment]
After updated blenderproc to 2.7.0 and change the demo.sh as:
![image](https://github.com/JiehongLin/SAM-6D/assets/56119958/570880d0-9062-48d2-bd9a-6ef834222a45)
The demo can be run successfully now.
I use:
PyTorch==2.2.1
cuda == 12.1
python == 3.8.15

**Comment by savidini** [comment]
@plusgrey can you maybe post your complete conda env, i.e. the output from `conda list`? 
I would be very grateful, as I am also working on making the demo run. Thanks and regards!

**Comment by dqj5182** [comment]
Wow! Works like a charm! Thanks for sharing :)

**Comment by jingchenlu** [comment]
Great! very good solution to my problem, thank you for sharing
