### ISSUE TITLE
How can I access the experimental results of '2D segmentation of unseen objects on BOP' under pure RGB settings?

### ISSUE THREAD

**Issue by csxieyc97** [JiehongLin/SAM-6D#39]
How can I access the experimental results of '2D segmentation of unseen objects on BOP' under pure RGB settings?

**Comment by Fupeng-Chu** [comment]
have solved? I followed the tutorial to run "python run_ineference.py dataset_name=hb" and only got the results_hb.json file. How can I get the RGB-D segmentation results in TableⅠ of the paper? Thanks for your help!
