### ISSUE TITLE
Instance Segmentation Results

### ISSUE THREAD

**Issue by NotEnterprising** [JiehongLin/SAM-6D#42]
Can you offer the SAM or FastSAM result json file?
Because I follow the instance segmentation instructions and i can't reproduce the results in the paper.

**Comment by NotEnterprising** [comment]
Solved, instance segmentation must run on single GPU.

**Comment by Fupeng-Chu** [comment]
I followed the tutorial to run "python run_ineference.py dataset_name=hb" and only got the results_hb.json file. How can I get the results in TableⅠ of the paper? Thanks for your help!
