### ISSUE TITLE
Training dataset problem.

### ISSUE THREAD

**Issue by plusgrey** [JiehongLin/SAM-6D#59]
Hi,

Could you please tell me that do you use the whole Megapose datasets, or only use the subsets of Megapose given by BOP via this link(https://www.paris.inria.fr/archive_ylabbeprojectsdata/bop-23-datasets/megapose-gso/train_pbr_web/)?

Thanks so much in advance.

**Comment by JiehongLin** [comment]
We use both GSO and ShapeNet datasets, as illustrated in the paper.

**Comment by plusgrey** [comment]
> We use both GSO and ShapeNet datasets, as illustrated in the paper.

Hi Jiehong, thanks for your reply. Do you mean the whole GSO and ShapeNet datasets, with 1040 parts?

**Comment by laowan666** [comment]
i want train some datasets, not all,   how do it?  
Thanks so much in advance.
