### ISSUE TITLE
Only RGB-D

### ISSUE THREAD

**Issue by tungyen** [JiehongLin/SAM-6D#70]
Is SAM6D able to do pose estimation only based on RGB-D image?

**Comment by JiehongLin** [comment]
Yes. It's caused by the GeoTransformers used in point matching and the positional encoding in the second stage.

**Comment by tungyen** [comment]
![image](https://github.com/user-attachments/assets/cc3f163c-0bb2-40ea-ad7d-22281e7c6d77)
But I saw we need the CAD file here. Or is the path of CAD file not necessary?
